# Globetrotter Travel MCP Server Configuration
spring:
  ai:
    mcp:
      server:
        name: globetrotter-mcp-server
        version: 1.0.0
        description: MCP Server for Globetrotter Travel Application
server:
    port: 8082

# Logging configuration
logging:
    level:
      root: DEBUG
      com.globetrotter.mcp: DEBUG
      org.springframework.web: DEBUG
      org.springframework.ai: DEBUG
      org.springframework.boot: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

services:
  travel:
    url: http://globetrotter-services:8080

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
